.SECONDARY:
TARGETS ?= \
	jumping_pc.thumb.c.bin \
	skipping_fn.thumb.c.bin \
	concolic-reg.thumb.S.bin \
	symbolic-flag-reg.arm.S.bin \
	flag-reg.arm.S.bin

all: build
build: $(TARGETS)

include ../../Makefile.common
